version: '3'

services:
  fix-mongodb-permissions:
    image: busybox
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
    - mongo-vol:/bitnami

  mongo:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_USERNAME=${DB_USER}
      - MONGODB_PASSWORD=${DB_PASSWORD}
      - MONGODB_DATABASE=${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo-vol:/bitnami
    depends_on:
      - fix-mongodb-permissions

  events:
    image: emqx/emqx:latest
    environment:
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_LOADED_PLUGINS=emqx_management,emqx_auth_mnesia,emqx_recon,emqx_retainer,emqx_dashboard
    ports:
      - 1883:1883
      - 18083:18083

  events-config:
    image: byrnedo/alpine-curl:latest
    environment:
      - EVENTS_USER=${EVENTS_USER?Variable EVENTS_USER not set}
      - EVENTS_PASSWORD=${EVENTS_PASSWORD?Variable EVENTS_PASSWORD not set}
    depends_on:
      - events
    entrypoint: ["/bin/sh", "-c"]
    command:
      - sleep 5;
        curl -i --basic -u admin:public -X POST http://events:8081/api/v4/mqtt_user -d '{"login":"$EVENTS_USER","password":"$EVENTS_PASSWORD","is_superuser":false}'

  infrastructure-console:
    image: registry.gitlab.com/castlecraft/building-blocks/infrastructure-console:edge
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - events
    links:
      - mongo
      - events
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - EVENTS_HOST=events
      - EVENTS_PORT=1883
      - EVENTS_USER=${EVENTS_USER}
      - EVENTS_PASSWORD=${EVENTS_PASSWORD}

volumes:
  mongo-vol:
  events-config-vol:
